name: CI
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-add-repository ppa:fish-shell/release-3
          sudo apt-get update
          sudo apt-get install -y fish redis-server redis-tools
      - name: Test
        run: |
          ./tests.fish
